In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [41]:
from sklearn.metrics import (
accuracy_score,
precision_score,
recall_score,
f1_score,
confusion_matrix,
roc_curve,
auc
)

In [42]:
data = load_breast_cancer()

In [43]:
x = data.data
y = data.target

print("Dataset Shape:",x.shape)
print("Classes: ",np.unique(y))

Dataset Shape: (569, 30)
Classes:  [0 1]


In [44]:
X_train,X_test, y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42, stratify=y)
# stratify : y , both the training and testing sets will become have approx the same percentages.

In [72]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

mle_model = LogisticRegression(
    penalty = None,
    max_iter = 10000, # change to 5000 as standard
    random_state=42
)

mle_model.fit(X_train,y_train)

y_pred_mle = mle_model.predict(X_test)

In [73]:
map_l1 = LogisticRegression(
penalty='l1', # L1 Regularization (Ridge Regulariation)
    C=1.0,
    solver ='liblinear', # solver is the optimization algorithm that find best coefficients
    max_iter=5000,
    random_state = 42,
)

map_l1.fit(X_train,y_train)
y_pred_l1 = map_l1.predict(X_test)

In [74]:
map_l2 = LogisticRegression(
penalty='l2', # L2 Regularization (Ridge Regulariation)
    C=1.0,
    solver ='lbfgs', # solver is the optimization algorithm that find best coefficients
    max_iter=5000,
    random_state = 42,
)

map_l2.fit(X_train,y_train)
y_pred_l2 = map_l2.predict(X_test)

In [75]:
def evaluate(model_name,y_true,y_pred):
    print("\n","="*40)
    print(model_name)
    print("="*40)

    print("Accuracy: ",accuracy_score(y_true,y_pred))
    print("Precision: ",precision_score(y_true,y_pred))
    print("Recall: ",recall_score(y_true,y_pred))
    print("F1: ",f1_score(y_true,y_pred))
          
    print("\n Confusion Matrix ")
    print(confusion_matrix(y_true,y_pred))
    
evaluate("MLE",y_test,y_pred_mle)
evaluate("MAP(L2)",y_test,y_pred_l2)
evaluate("MAP(L1)",y_test,y_pred_l1)


MLE
Accuracy:  0.9736842105263158
Precision:  0.9726027397260274
Recall:  0.9861111111111112
F1:  0.9793103448275862

 Confusion Matrix 
[[40  2]
 [ 1 71]]

MAP(L2)
Accuracy:  0.9649122807017544
Precision:  0.9594594594594594
Recall:  0.9861111111111112
F1:  0.9726027397260274

 Confusion Matrix 
[[39  3]
 [ 1 71]]

MAP(L1)
Accuracy:  0.9649122807017544
Precision:  0.9594594594594594
Recall:  0.9861111111111112
F1:  0.9726027397260274

 Confusion Matrix 
[[39  3]
 [ 1 71]]


In [76]:
print("number of zero Coefficients")
print("MLE:",np.sum(mle_model.coef_[0]==0))
print("MAP L2:",np.sum(map_l2.coef_[0]==0))
print("MAP L1:",np.sum(map_l1.coef_[0]==0))

number of zero Coefficients
MLE: 0
MAP L2: 0
MAP L1: 20


In [81]:
results = pd.DataFrame(
    columns=["model","Accuracy","Precision","Recall","F1 Score"]
)
models = [
    ("MLE",mle_model,y_pred_mle),
    ("MAP L2",map_l2,y_pred_l2),
    ("MAP L1",map_l1,y_pred_l1)
]

for name, model ,pred in models:
    results.loc[len(results)] = [
        name, 
        accuracy_score(y_test,pred),
        precision_score(y_test,pred),
        recall_score(y_test,pred),
        f1_score(y_test,pred)
    ]

print(results)
        

    model  Accuracy  Precision    Recall  F1 Score
0     MLE  0.973684   0.972603  0.986111  0.979310
1  MAP L2  0.964912   0.959459  0.986111  0.972603
2  MAP L1  0.964912   0.959459  0.986111  0.972603
